import React, { useState, useRef } from 'react'
import { Info } from 'lucide-react'

interface TokenUsage {
  input: number
  output: number
  cacheRead?: number
  cacheWrite?: number
}

interface ModelPricing {
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
}

// Prices in USD per 1M tokens.
// Source: https://www.anthropic.com/pricing — verify for models released after Aug 2025.
function getPricing(model?: string): ModelPricing {
  const m = (model ?? '').toLowerCase()
  if (m.includes('opus')) {
    return { input: 15, output: 75, cacheRead: 1.5, cacheWrite: 18.75 }
  }
  if (m.includes('haiku')) {
    return { input: 0.8, output: 4, cacheRead: 0.08, cacheWrite: 1 }
  }
  // Sonnet and unknown models
  return { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 }
}

function computeCost(usage: TokenUsage, pricing: ModelPricing): number {
  return (
    usage.input * pricing.input +
    usage.output * pricing.output +
    (usage.cacheRead ?? 0) * pricing.cacheRead +
    (usage.cacheWrite ?? 0) * pricing.cacheWrite
  ) / 1_000_000
}

interface Row {
  label: string
  count: number
  desc: string
  colorClass: string
}

export function TokenUsagePopover({ usage, model }: { usage: TokenUsage; model?: string }) {
  const [visible, setVisible] = useState(false)
  const [pos, setPos] = useState({ top: 0, left: 0 })
  const ref = useRef<HTMLSpanElement>(null)

  const pricing = getPricing(model)
  const cost = computeCost(usage, pricing)

  const rows: Row[] = [
    {
      label: 'Input',
      count: usage.input,
      desc: 'Newly processed tokens, not served from cache',
      colorClass: 'text-zinc-300',
    },
    ...(usage.cacheWrite
      ? [{
          label: 'Cache write',
          count: usage.cacheWrite,
          desc: 'Tokens written to the prompt cache this turn',
          colorClass: 'text-amber-400',
        }]
      : []),
    ...(usage.cacheRead
      ? [{
          label: 'Cache read',
          count: usage.cacheRead,
          desc: 'Tokens served from cache (10× cheaper than input)',
          colorClass: 'text-emerald-400',
        }]
      : []),
    {
      label: 'Output',
      count: usage.output,
      desc: 'Tokens generated by the model',
      colorClass: 'text-zinc-300',
    },
  ]

  const handleMouseEnter = () => {
    if (ref.current) {
      const rect = ref.current.getBoundingClientRect()
      setPos({ top: rect.top - 8, left: rect.left })
    }
    setVisible(true)
  }

  return (
    <>
      <span
        ref={ref}
        className="flex items-center gap-1.5 cursor-default select-none"
        onMouseEnter={handleMouseEnter}
        onMouseLeave={() => setVisible(false)}
        onClick={e => e.stopPropagation()}
      >
        <span className="text-zinc-600">{usage.input.toLocaleString()}↓</span>
        <span className="text-zinc-600">{usage.output.toLocaleString()}↑</span>
        <span className="text-zinc-500">~${cost.toFixed(3)}</span>
        <Info size={10} className="text-zinc-600 hover:text-zinc-400 transition-colors" />
      </span>

      {visible && (
        <div
          className="fixed z-50 pointer-events-none"
          style={{ top: pos.top, left: pos.left, transform: 'translateY(-100%)' }}
        >
          <div className="mb-2 bg-zinc-800 border border-zinc-700 rounded-lg p-3 shadow-2xl text-xs w-72">
            <p className="text-zinc-300 font-semibold mb-2.5">Token Usage</p>
            <div className="space-y-1.5">
              {rows.map(row => (
                <div key={row.label} className="grid grid-cols-[80px_1fr_auto] items-baseline gap-2">
                  <span className={`font-medium ${row.colorClass}`}>{row.label}</span>
                  <span className="text-zinc-500 leading-tight">{row.desc}</span>
                  <span className="text-zinc-300 tabular-nums text-right">{row.count.toLocaleString()}</span>
                </div>
              ))}
            </div>
            <div className="mt-2.5 pt-2 border-t border-zinc-700 flex justify-between items-center">
              <span className="text-zinc-500">Estimated cost</span>
              <span className="text-zinc-300 font-medium tabular-nums">~${cost.toFixed(3)}</span>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
